name: CI commit action

on:
  push:
    branches-ignore: [ 'gh-pages' ]

  pull_request:
    branches-ignore: [ 'gh-pages' ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ '20.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies and build
        run: for sample in sat sprite tilemap-manager font platformer rigidbody; do cd $sample; npm install; npm run build:prod; rm -rf node_modules; cd ..; done

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
